[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bodmer/TFT_eSPI


build_flags =
    -I include
    ; -D ST7789_DRIVER


